[project]
name = "angstromchat-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "kernels>=0.16.0",
    "numpy>=2.2.6",
    "pyarrow>=25.0.0",
    "requests>=2.34.2",
    "rustbpe>=0.1.0",
    "tiktoken>=0.13.0",
    "torch>=2.12.1",
    "wandb>=0.28.2",
]
